Update README.md
HTTPArchive/almanac.httparchive.org pull request #1135
Opened 2020-07-31 13:55 UTC by jrharalson

Initial check-in PR/placeholder

2020-09-03 22:26 UTC, rviscomi commented
Hey @jrharalson. I know this isn't marked for review yet, but I wanted to give you a quick heads up about something. There's a new SQL naming convention this year where we'll be naming the queries more descriptively based on what they're analyzing as opposed to chapter/metric numbers. So for example `13_01.sql` could be `top_vendors.sql`. This makes them more discoverable later.

2020-09-16 22:34 UTC, rviscomi commented
Be sure to update this from "Draft" to "Ready for review" so we can get more eyes on it

2020-09-20 00:01 UTC, rviscomi requested changes

2020-09-20 00:01 UTC, rviscomi commented on sql/2020/16_Ecommerce/top_cdn_bydevice_vendor_wapp.sql
> +    `httparchive.sample_data.technologies_*`
And group by `_TABLE_SUFFIX`
```suggestion
    `httparchive.technologies.2020_08_01_*`
```

2020-09-22 21:15 UTC, jrharalson reviewed
Thanks for the feedback. Made a few updates and push a few updates that were stuck pending a check-in. Need to rework the LCP sql later.

2020-09-28 05:30 UTC, rviscomi commented
@jrharalson sounds good let me know when this is ready for another review

2020-09-28 23:34 UTC, rviscomi commented on sql/2020/16_Ecommerce/lcp_byvendor_bydevice.sql
> +    AVG(ROUND(SAFE_DIVIDE(fast_lcp, fast_lcp + avg_lcp + slow_lcp) * 100, 2)) AS fast,
The second suggestion can be easily adapted from the [CMS chapter's query](https://github.com/HTTPArchive/almanac.httparchive.org/blob/7d373c3fa1ba0b3d78ed41484115552a52e4350e/sql/2020/15_CMS/core_web_vitals_passing.sql#L51) by replacing `WHERE category = 'CMS'` with `'Ecommerce'`. This gives you LCP, FID, CLS, and the overall CWV assessment.

You can also adapt [this query](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2020/15_CMS/core_web_vitals_distribution.sql) of good/ni/poor speeds for each metric.

2020-10-06 01:26 UTC, rviscomi commented
@jrharalson how's this coming along?

2020-10-10 14:54 UTC, jrharalson commented
Updated to the latest Crux style

2020-10-10 15:45 UTC, rviscomi approved these changes
Just one small correction, then this should be good to go

2020-10-10 15:45 UTC, rviscomi commented on sql/2020/16_Ecommerce/pagestats_image_bydevice_format.sql
> +  (SELECT _TABLE_SUFFIX AS client, url AS page FROM `httparchive.technologies.2020_07_01_*` WHERE category = 'Ecommerce')
```suggestion
  (SELECT _TABLE_SUFFIX AS client, url AS page FROM `httparchive.technologies.2020_08_01_*` WHERE category = 'Ecommerce')
```

2020-10-15 22:54 UTC, rviscomi approved these changes

2020-10-15 22:55 UTC, merged