Translating 2019 Fonts chapter to Spanish
HTTPArchive/almanac.httparchive.org pull request #1234
Opened 2020-08-20 18:15 UTC by c-torres

Progress on #498

2020-08-20 23:11 UTC, bazzadp requested changes
Looks pretty good to me from a technical side!

A few questions/corrections.

Also would it be possible for you to translate Zach's Bio at same time as it appears at the bottom of this page?

https://github.com/HTTPArchive/almanac.httparchive.org/blob/3f06faaa5792fcac9881ae6415ff855e7f1021fa/src/templates/es/2019/base.html#L202

And on a similar note can we also translate the Featured Quote from this chapter:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/3f06faaa5792fcac9881ae6415ff855e7f1021fa/src/templates/es/2019/featured_chapters.html#L22-L24

And also enable this Featured Chapter by changing line 1 of that template:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/3f06faaa5792fcac9881ae6415ff855e7f1021fa/src/templates/es/2019/featured_chapters.html#L1

to:
```
{%- set featured_chapter = ("third-parties","fonts") | random %}
```

2020-08-20 23:11 UTC, bazzadp commented on src/content/es/2019/fonts.md
> +title: Fonts
Should this be Fuentes?

```suggestion
title: Fuentes
```

2020-08-20 23:11 UTC, bazzadp commented on src/content/es/2019/fonts.md
> +  <div id="fig19-description" class="visually-hidden">Bar chart showing the usage of the font-variation-settings property. 42% of properties on desktop pages are set to the "opsz" value, 32% to "wght
Missed the translation here

2020-08-20 23:47 UTC, c-torres commented
@bazzadp thanks for the feedback, I believe all the suggestions have been applied.

2020-08-20 23:53 UTC, bazzadp commented
Wow that was quick! Thanks!

We really should translate the bios and featured chapters of the other translated chapters at some point. But we'll leave that for another day and another PR.

2020-08-20 23:54 UTC, bazzadp approved these changes

2020-08-23 17:45 UTC, bazzadp commented
Planning a release this evening so gonna merge this as is. @garcaplay is you get a chance to review at a later date then feel free to comment here, or open a new PR.

2020-08-23 17:59 UTC, merged

2020-08-23 18:31 UTC, garcaplay commented
Hi guys! Sorry for the late response! As soon as I have the chance will review this new code (with a more language oriented view, as I'm pretty sure you covered a 100% of the technical perspective on your review ;) ) and if find something else to fix will let you know!

2020-08-23 18:53 UTC, bazzadp commented
No problems!

Just to let you know when I’m doing a release I often will merge unreviewed translations we have queued up at the time. While of course it’s best to get a translation reviewed by another where possible, I do appreciate that people are doing this on their own spare time so have to squeeze it in where they can. In the meantime I figure a translation by a native speaker is better than no translation at all, even if it may contain some typos or things that could be phrased better. We can always tweak it later. So I would rather include in the release than not. At the same time don’t want to pressure reviewers or demand a review by a set time, so figure this is the best way.

Hopefully that explains my thinking and do let me know if you’ve any suggestions on better ways or working?

Thanks again (to both of you!) for your efforts on this!