Add Analysis By byline
HTTPArchive/almanac.httparchive.org pull request #1334
Opened 2020-10-01 16:46 UTC by bazzadp

@rviscomi I can't find it now, but think we said we'd give the Analysts a byline this year in the chapters?

![Analysis By Byline](https://user-images.githubusercontent.com/10931297/94838608-be604c00-040d-11eb-8705-ead31aea5c01.png)

It appears before the Translator if any exists:

![Analysis By Byline before Translated by](https://user-images.githubusercontent.com/10931297/94838557-b0123000-040d-11eb-8a26-5c46017f690f.png)

Will add the rest of the 2019 analysts [from the 2019 PM spreadsheet](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/edit#gid=2048624140) once this PR is reviewed.

2020-10-01 17:59 UTC, rviscomi approved these changes
LGTM thanks!

2020-10-01 18:16 UTC, bazzadp commented
Cool. Will add the rest of the chapters now.

@HTTPArchive/translators could some fo you checkout the translations in base.html in your respective languages if you get a chance before I merge?

2020-10-01 18:59 UTC, borisschapira requested changes

2020-10-01 18:59 UTC, borisschapira commented on src/templates/fr/2019/base.html
> +{% block analysis_by_before %}Analyse par{% endblock %}
```suggestion
{% block analysis_by_before %}Analysé par{% endblock %}
```

2020-10-01 18:59 UTC, borisschapira commented on src/templates/fr/2019/base.html
> +{% block analysis_by_before %}Analyse par{% endblock %}
Other verbs use the "participe passé", so this one should be using it too.

2020-10-01 19:58 UTC, chengxicn approved these changes
changed 分析员 to 分析者

2020-10-02 01:56 UTC, HakaCode approved these changes
all right

2020-10-06 09:14 UTC, merged