Check if audit is applicable
HTTPArchive/almanac.httparchive.org pull request #1338
Opened 2020-10-04 20:47 UTC by obto

Quick update to the LH metric to check if the audit was applicable to a site or not. Only applicable sites should be counted towards the total, or you end up with incorrect %'s of sites meeting each audit.

2020-10-04 20:50 UTC, bazzadp requested changes
Thanks - good spot. And just [after I'd tweeted out about this](https://twitter.com/tunetheweb/status/1312774697520697345?s=20) :-(

One suggestion is to keep total number of pages. This is good for identifying LH5 scores (some still creeping in there even in September).

2020-10-04 20:50 UTC, bazzadp commented on sql/2020/14_PWA/lighthouse_pwa_audits.sql
> +  COUNTIF(audits.score IS NOT NULL) AS total_applicable,
```suggestion
  count(0) AS total,
  COUNTIF(audits.score IS NOT NULL) AS total_applicable,
```

2020-10-12 18:47 UTC, bazzadp commented on sql/2020/14_PWA/lighthouse_pwa_audits.sql
> +  COUNTIF(audits.score IS NOT NULL) AS total_applicable,
Gentle ping @obto !

2020-10-13 02:09 UTC, obto commented on sql/2020/14_PWA/lighthouse_pwa_audits.sql
> +  COUNTIF(audits.score IS NOT NULL) AS total_applicable,
LGTM. Added to the PR

2020-10-13 06:53 UTC, bazzadp approved these changes
Small capitalisation issue but will change that and merge.

I was more letting you know this in case you wanted to change https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2020/08_Accessibility/lighthouse_a11y_audits.sql

Will add to this PR and merge.

2020-10-13 06:53 UTC, bazzadp commented on sql/2020/14_PWA/lighthouse_pwa_audits.sql
> +  count(0) AS total,
```suggestion
  COUNT(0) AS total,
```

2020-10-13 12:30 UTC, merged