Translate 2020 CSS chapter to Portuguese
HTTPArchive/almanac.httparchive.org pull request #2058
Opened 2021-03-05 00:45 UTC by emanuelgsouza

Makes progress on #505

2021-03-05 18:18 UTC, bazzadp requested changes
Not an easy chapter to edit as it's our biggest one!

A few small corrections but other than that looks good to me from a technical front.

2021-03-05 18:18 UTC, bazzadp commented on src/content/pt/2020/css.md
> +Mas para que os IDs são usados? Acontece que os IDs mais populares são estruturais: `#content`, `#footer`, `#header`, `#main`, embora existam [elementos HTML correspondentes](https://developer.mozill
```suggestion
Mas para que os IDs são usados? Acontece que os IDs mais populares são estruturais: `#content`, `#footer`, `#header`, `#main`, embora existam [elementos HTML correspondentes](https://developer.mozilla.org/pt-BR/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure#elementos_de_layout_do_html_em_mais_detalhes) que poderiam ser utilizados como seletores ao mesmo tempo em que melhoram a marcação semântica.
```

2021-03-05 18:18 UTC, bazzadp commented on src/content/pt/2020/css.md
> +Quando a função [`calc()`](https://developer.mozilla.org/pt-BR/docs/Web/CSS/calc()) foi introduzida para realizar cálculos entre diferentes unidades no CSS, foi uma revolução. Anteriormente, apenas o
```suggestion
Quando a função [`calc()`](https://developer.mozilla.org/pt-BR/docs/Web/CSS/calc()) foi introduzida para realizar cálculos entre diferentes unidades no CSS, foi uma revolução. Anteriormente, apenas os pré-processadores eram capazes de realizar tais cálculos, mas os resultados eram limitados a valores estáticos e não confiáveis, uma vez que faltava o contexto dinâmico que muitas vezes é necessário.
```

2021-03-05 18:18 UTC, bazzadp commented on src/content/pt/2020/css.md
> +- E outra estranheza: a propriedade `font-rendering` aparece em 2.575 páginas. No entanto, não podemos encontrar evidências da existência de tal propriedade, com ou sem um prefixo. Existe o não padrã
```suggestion
- E outra estranheza: a propriedade `font-rendering` aparece em 2.575 páginas. No entanto, não podemos encontrar evidências da existência de tal propriedade, com ou sem um prefixo. Existe o não padrão [`-webkit-font-smoothing`](https://medium.com/better-programming/improving-font-rendering-with-css-3383fc358cbc) que é extremamente popular, aparecendo em 3 milhões de sites, ou cerca de 49% das páginas, mas `font-rendering` não é suficientemente próximo para ser um erro de ortografia. Existe [`text-rendering`](https://developer.mozilla.org/pt-BR/docs/Web/CSS/text-rendering) que é usado em cerca de 100K de sites, portanto, é concebível que 2,5K e todos os desenvolvedores se lembraram erroneamente e cunharam um portmanteau de `font-smoothing` e `text-rendering`.
```

2021-03-09 00:01 UTC, emanuelgsouza commented
Hey @bazzadp , I implemented the requested changes. Could you take a look again? Thank you for your review.

2021-03-09 09:30 UTC, bazzadp approved these changes

2021-03-09 09:31 UTC, bazzadp commented
All good to merge from my side.

@HTTPArchive/portuguese-translators if anyone is able to review this let me know. Otherwise I'll merge in next few days.

2021-03-12 09:53 UTC, merged