Translation of the 2020 mobile web chapter to Dutch
HTTPArchive/almanac.httparchive.org pull request #2064
Opened 2021-03-11 18:03 UTC by noah-vdv

#1750 
Kept mSpeed as is but I can change it if needed

2021-03-11 18:45 UTC, bazzadp requested changes
Spotted a few issues

2021-03-11 18:45 UTC, bazzadp commented on src/content/nl/2020/mobile-web.md
> +  caption='Pagina's met afbeeldingen van het juiste formaat',
Need to change caption to double quotes. And I can't see any reason for the extra `alt` so can we remove that (in English too if possible):

```suggestion
  caption="Pagina's met afbeeldingen van het juiste formaat",
```

2021-03-11 18:45 UTC, bazzadp commented on src/content/nl/2020/mobile-web.md
> +Volgens <a hreflang="en" href="https://www.thirdpartyweb.today/">thirdpartyweb.today</a>, is <a hreflang="en" href="https: //www.optimizely.com">Optimizely</a> het meest populaire product van derden
Extra space:

```suggestion
Volgens <a hreflang="en" href="https://www.thirdpartyweb.today/">thirdpartyweb.today</a>, is <a hreflang="en" href="https://www.optimizely.com">Optimizely</a> het meest populaire product van derden voor A/B-testen, het wordt gebruikt op meer dan 20.000 pagina's.
```

2021-03-11 18:45 UTC, bazzadp commented on src/content/nl/2020/mobile-web.md
> +### gegevensbronnen
Capital G?

```suggestion
### Gegevensbronnen
```

2021-03-11 18:45 UTC, bazzadp commented on src/content/nl/2020/mobile-web.md
> +Vergeleken met desktop zijn transacties op mobiele apparaten foutgevoelig en vervelend, aangezien gebruikers persoonlijke informatie moeten invoeren met behulp van kleine toetsenborden en schermforma
Remove extra spaces:

```suggestion
Vergeleken met desktop zijn transacties op mobiele apparaten foutgevoelig en vervelend, aangezien gebruikers persoonlijke informatie moeten invoeren met behulp van kleine toetsenborden en schermformaten. Afrekenstromen moeten eenvoudig en kort zijn om gebruikersfrustratie, of erger nog, verlating te voorkomen. 27% van de gebruikers verlaat het afrekenen vanwege een <a hreflang="en" href="https://www.smashingmagazine.com/2018/08/best-practices-for-mobile-form-design/">"te lang / ingewikkeld afrekenproces"</a>. 35% van de gebruikers verlaat het afrekenen als een winkel <a hreflang="en" href="https://baymard.com/blog/ecommerce-checkout-usability-report-and-benchmark">geen gastafrekenen aanbiedt</a>.
```

2021-03-11 18:45 UTC, bazzadp commented on src/content/nl/2020/mobile-web.md
> +Een <a hreflang="en" href="https://web.dev/milliseconds-make-millions/">recente studie</a> toonde aan dat 0,1s mSpeed verbetering de conversieratio's met +8,4% verhoogde voor winkelsites en +10,1% vo
Let's change to mobile speed (can you change English too?)

```suggestion
Een <a hreflang="en" href="https://web.dev/milliseconds-make-millions/">recente studie</a> toonde aan dat 0,1s mobile speed verbetering de conversieratio's met +8,4% verhoogde voor winkelsites en +10,1% voor reissites.
```

2021-03-12 09:52 UTC, bazzadp approved these changes

2021-03-12 09:55 UTC, merged

2021-03-12 10:28 UTC, noah-vdv commented
> And I can't see any reason for the extra `alt` so can we remove that (in English too if possible):

So in future cases, if there's an `alt` and a `caption` we just remove the `alt`?

2021-03-12 10:45 UTC, bazzadp commented
The `caption` is used as the `alt`, when it's not explicitly provided.

The `caption` is what is displayed on screen (and also what's used by screen readers since we expose that with `aria-labelledby` which overrides the `alt`).

The `alt` is used when image fails to download and also for SEO purposes — hough with a decent filename it's probably a bit redundant to be honest, but we didn't use decent filenames for the 2019 edition (we got better this year).

The reason we have both is to allow them to be different of they need to be. Why would you want a different `alt`? For a few reasons:
1. If the caption contains HTML (e.g. code formatting, or `<span lang="en"></span>` tags). There's some dispute whether an `alt` should have HTML or not, but [I agree with this answer](https://stackoverflow.com/a/18856889/2144578) and think not, but `caption` can have it.
2. Kind of an extension to that, if the caption contains a source reference, then you could remove the link from the alt ([example])(https://almanac.httparchive.org/en/2020/capabilities#fig-1). The mobile web uses them but as plain text ([example](https://almanac.httparchive.org/en/2020/mobile-web#fig-7)). Now you've made me think about this some more, I think it should the best answer is a combination of both - have the plain text source as the `alt`, but then the hyperlinked version as the `caption`.
3. Something else I've not thought of yet :-)

So yes if the `alt` and the `caption` are exactly the same (as they were in a couple of places here), then there is no benefit to having both as the template will automatically copy the `caption` into the `alt` and so I think we should remove to avoid duplication and having to translate the same thing twice.

Make sense?

All this is getting very picky of me btw! But good to have standards.