Turkish Translation of 2019 and 2020 Contributors Pages
HTTPArchive/almanac.httparchive.org pull request #2122
Opened 2021-04-07 00:00 UTC by fatmabadri

Makes progress on #1044

2021-04-07 06:02 UTC, bazzadp requested changes
Looks good, but suggested removing the entity coding from the meta data in case they cause problems.

2021-04-07 06:02 UTC, bazzadp commented on src/templates/tr/2019/contributors.html
> +{% block description %}2019 Web Almanac&#8217;a Analistler, Yazarlar, Beyin Takımı, Tasarımcılar, Geliştiriciler, Editörler, İnceleyiciler ve Çevirmenler olarak katkıda bulunan {{ config.contributors
Meta data should be pain text as it's not rendered as HTML so would prefer not to use smart quotes like `&#8217` if we can avoid it.

```suggestion
{% block title %}2019 Katkıda bulunanlar | HTTP Archive'dan Web Almanac{% endblock %}

{% block description %}2019 Web Almanac'a Analistler, Yazarlar, Beyin Takımı, Tasarımcılar, Geliştiriciler, Editörler, İnceleyiciler ve Çevirmenler olarak katkıda bulunan {{ config.contributors.items() | length }} kişi.{% endblock %}
```

2021-04-07 06:02 UTC, bazzadp commented on src/templates/tr/2020/contributors.html
> +{% block description %}{{ year }}Web Almanac&#8217;a Analistler, Yazarlar, Tasarımcılar, Geliştiriciler, Editörler, Liderler, İnceleyiciler ve Çevirmenler olarak katkıda bulunan {{ config.contributor
```suggestion
{% block title %}{{ year }} Katkıda bulunanlar | HTTP Archive'dan Web Almanac{% endblock %}

{% block description %}{{ year }}Web Almanac'a Analistler, Yazarlar, Tasarımcılar, Geliştiriciler, Editörler, Liderler, İnceleyiciler ve Çevirmenler olarak katkıda bulunan {{ config.contributors.items() | length }}kişi.{% endblock %}
```

2021-04-08 00:19 UTC, fatmabadri reviewed
remove the entity code from the meta data

2021-04-08 08:10 UTC, merged