Fonts 2021 sql
HTTPArchive/almanac.httparchive.org pull request #2338
Opened 2021-09-20 21:43 UTC by konfirmed

2021-09-21 10:18 UTC, tunetheweb commented
@konfirmed is this good to review no or still work in progress?

If it's still WIP can you switch it to a draft PR for now, and also include the list of metrics with those that have been done and those that are still to do, so we can get a sense of how far through this is?

See some of the other PRs as examples:

![image](https://user-images.githubusercontent.com/10931297/134154002-ef67ec05-2a00-4e6b-8af8-2ba4c559d409.png)

Also FYI @jessthebp as think she was planning on looking at these queries too.

2021-09-21 17:10 UTC, konfirmed commented
It is still work in progress, will revert. Will reach out to Jess. Thanks.

2021-09-21 17:15 UTC, tunetheweb commented
Well happy for you to reopen this and leave it as draft. As I say we actually like that cause we can see work is being done - which is good for us to avoid panicking that no ones working on a chapters analysis!! 😁

Once it’s ready for review you can then take it out of draft.

2021-09-21 17:19 UTC, rviscomi commented
Reopened and set to draft. Thanks for kicking this off @konfirmed!

2021-10-02 06:10 UTC, rviscomi commented
@konfirmed @jessthebp is there anything I can do to help unblock this PR?

2021-10-04 03:10 UTC, rviscomi requested changes
Just a few nits, thanks for working on these @konfirmed!

2021-10-04 03:10 UTC, rviscomi commented on sql/2021/fonts/fonts_format.sql
> +  type = 'font' AND mimeType != '' AND date = '2021-07-01'
```suggestion
  date = '2021-07-01' AND
  type = 'font' AND
  mimeType != ''
```

2021-10-04 03:10 UTC, rviscomi commented on sql/2021/fonts/fonts_format.sql
> +  client, pct DESC
```suggestion
  client,
  pct DESC
```

2021-10-04 03:10 UTC, rviscomi commented on sql/2021/fonts/variable_font_axes_used.sql
> +  client, axis, num_axis
```suggestion
  client,
  axis,
  num_axis
```

2021-10-04 17:49 UTC, rviscomi approved these changes

2021-10-04 17:49 UTC, rviscomi commented
Merging 🚀

If there are any additional queries needed for this chapter, please reopen a new PR.

2021-10-04 17:50 UTC, merged