Security chapter
HTTPArchive/almanac.httparchive.org pull request #2578
Opened 2021-11-23 11:00 UTC by SaptakS

Refs: #2150

2021-11-23 15:30 UTC, rviscomi commented
@SaptakS mark this "ready for review" when ready

2021-11-23 15:36 UTC, SaptakS commented
@rviscomi Yep. Just waiting on a few things. Should be ready for review by tonight hopefully.

2021-11-24 00:08 UTC, tunetheweb requested changes
A fantastic conversion!

I've drop a few comments (mostly editing nits)that will just make the subsequent copy edit PR a lot smaller.

@tomvangoethem @nrllh you happy to merge this?

2021-11-24 08:00 UTC, SaptakS commented on src/content/en/2021/security.md
> +Currently, we see that 92.3% of total requests for websites on desktop and 91.3% of total requests for websites on mobile are being served using HTTPS. We see an [increasing number of certificates](h
This is only for external links, right?

2021-11-24 08:04 UTC, tunetheweb commented on src/content/en/2021/security.md
> +Currently, we see that 92.3% of total requests for websites on desktop and 91.3% of total requests for websites on mobile are being served using HTTPS. We see an [increasing number of certificates](h
Correct. We remain optimistic that the internal links will all be translated (someday!).

Also it’s unnecessary (and preferred not to have) for Twitter links (they offer an auto translate option on Tweets), MDN (they have most pages translated to at least one language and we’ll show the `(en)` UI based on the `en-US` in the URL) and Wikipedia (same).

2021-11-24 09:20 UTC, SaptakS commented
@tunetheweb addressed all the above comments.

2021-11-24 16:58 UTC, tunetheweb commented
OK made a few more tweaks but think this is good to merge. There'll be a copy edit after this and then we're good.

Here's how it looks now: https://20211124t165615-dot-webalmanac.uk.r.appspot.com/en/2021/security

2021-11-24 17:03 UTC, merged