2021 javascript japanese translation
HTTPArchive/almanac.httparchive.org pull request #2718
Opened 2021-12-12 01:13 UTC by ksakae1216

Please review for me.
Part of #586

2021-12-14 19:49 UTC, tunetheweb commented on src/content/ja/2021/javascript.md
> +{{ figure_markup(
```suggestion
[根本的な原因](https://twitter.com/rick_viscomi/status/1331735748060524551?s=20)を見つけ、[今後そのような使い方をしないようにする](https://twitter.com/Kraft/status/1336772912414601224?s=20)というアクションアイテムも用意されています。

{{ figure_markup(
```

2021-12-14 20:33 UTC, tunetheweb requested changes
Looks good @ksakae1216 !

Just one small missed translation

2021-12-14 20:37 UTC, tunetheweb commented on src/content/ja/2021/javascript.md
> +  sheets_gid="183546956",
```suggestion
  sheets_gid="1113974683",
```

2021-12-14 22:39 UTC, ksakae1216 commented on src/content/ja/2021/javascript.md
> +昨年の結果では、同じスクリプトに `async` と `defer` の両方の属性を使用しているウェブサイトがあるというアンチパターンが観察されました。これは、ブラウザがサポートしている場合は `async` にフォールバックし、IE8とIE9のブラウザでは `defer` を使用するというものです。しかし、ほとんどのサイトでは、サポートされているすべてのブラウザで`async`が優先されるため
Thanks, I missed.

2021-12-14 22:48 UTC, ksakae1216 commented on src/content/ja/2021/javascript.md
> +  caption="モバイルページでの同期および非同期AJAXリクエストの使用について",
Yes, I corrected.
And line 714 corrected.

2021-12-14 23:20 UTC, ksakae1216 commented
I don't push, Because Token expired.
And I have problem. Please wait.

2021-12-14 23:25 UTC, tunetheweb commented
OK. Feel free to enter the edits as comments as if doing a review and can then accept them in GitHub. If that's easier.

2021-12-15 12:40 UTC, tunetheweb approved these changes
LGTM! Thanks again for your continual work on this. Hope to get this out in next day or two once the final 2021 English Chapter is merged.

2021-12-15 12:40 UTC, merged