Caching 2022 queries
HTTPArchive/almanac.httparchive.org pull request #2941
Opened 2022-05-23 10:26 UTC by kevinfarrugia

Progress on #2902 .

_Pending Outline_

2022-06-20 09:03 UTC, kevinfarrugia commented
I will update all queries for the June 2022 run. Let me know if we wish to add anything.

2022-08-01 11:34 UTC, tunetheweb requested changes
Only one comment

2022-08-01 11:34 UTC, tunetheweb commented on sql/2022/caching/header_trends.sql
> +    `httparchive.summary_requests.2021_05_01_*`
Shouldn't this be:

```suggestion
    `httparchive.summary_requests.2021_07_01_*`
```

2022-08-02 07:37 UTC, tunetheweb approved these changes

2022-08-02 07:37 UTC, merged