JavaScript 2022 queries
HTTPArchive/almanac.httparchive.org pull request #2942
Opened 2022-05-23 11:21 UTC by kevinfarrugia

Progress on #2880 .

**How much JavaScript do we load?**
- [ ] Requests per page
- [ ] Bytes per page
- [ ] Unused scripts (or unused bytes per page)

**How is JavaScript processed?**
- [ ] Bundlers
- [ ] Transpilers

**How is JavaScript requested**
- [ ] `async` and `defer`
- [ ] `module` and `nomodule`
- [ ] `preload`, `prefetch` and `modulepreload`
- [ ] JavaScript in the `<head>` (render blocking JavaScript (excluding inline))
- [ ] Injected scripts
- [ ] First-party vs third-party
  - [ ] Requests per page
  - [ ] Bytes per page
  - [ ] Resource hints
    - [ ] dns-prefetch
    - [ ] preconnect
- [ ] Dynamic import
- [ ] Web workers
- [ ] Worklets
  - [ ] PaintWorklet
  - [ ] AudioWorklet

**How is JavaScript delivered?**
- [ ] Compression
- [ ] Minification
- [ ] Source maps

**Responsiveness**
- [ ] Metrics
- [ ] Long tasks/blocking time
- [ ] `requestIdleCallback` and `queueMicrotask`
- [ ] Synchronous AJAX

**How is JavaScript used?**
- [ ] Libraries and frameworks
  - [ ] Library usage
  - [ ] Libraries used together
  - [ ] Security Vulnerabilities
- [ ] Web components and shadow DOM

2022-05-25 12:53 UTC, malchata commented
@kevinfarrugia, I made a couple edits on this to break down the "Responsiveness APIs" section, as well as to detail the exact responsiveness metrics we wanted. We may also be able to jettison the "Long tasks/blocking time" section since we're capturing TBT.

2022-05-25 14:40 UTC, kevinfarrugia commented
`document.write` is flagged in a a Lighthouse audit, so that should be easy enough. https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/dobetterweb/no-document-write.js

For the Responsiveness, I think (TBC) we should be able to get number of long tasks, duration of long tasks and TBT from lab tests. INP and FID will come from the CruX dataset.

2022-05-25 14:49 UTC, malchata commented
> `document.write` is flagged in a a Lighthouse audit, so that should be easy enough. https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/dobetterweb/no-document-write.js

_Awesome._ I think this will be a nice add, since we've been advising against `document.write` for a while now.

> On the third-party chapter we are measuring `document.write` by third-parties.

Good to know!

> For the Responsiveness, I think (TBC) we should be able to get number of long tasks, duration of long tasks and TBT from lab tests. INP and FID will come from the CruX dataset.

Now that I think of it, discrete info on long tasks are good. So let's capture those like we originally planned. It would be good contextualizing information alongside of metrics (even TBT, which doesn't measure the number of blocking tasks, just the sum of all blocking time at startup).

2022-05-26 20:09 UTC, kevinfarrugia commented on sql/2022/javascript/tbt.sql
> +    `httparchive.lighthouse.2022_04_01_mobile`
Thanks. At the moment I'm just putting something quick together to make sure I do not need any custom metrics, then I will brush up on all queries after the crawl.

2022-06-17 17:14 UTC, siakaramalegos commented
Great job on the progress so far! Could you update the checklist above so we can get an idea of how much is left to go?

2022-06-20 09:04 UTC, kevinfarrugia commented
Yes, I will update all queries to June 2022, verify the data and update the PR by mid next week.

2022-08-02 22:28 UTC, kevinfarrugia commented on sql/2022/javascript/tbt.sql
> +    `httparchive.lighthouse.2022_04_01_mobile`
@rviscomi Does this still apply? Should we run Lighthouse queries for both desktop & mobile?

2022-08-03 03:18 UTC, rviscomi commented on sql/2022/javascript/tbt.sql
> +    `httparchive.lighthouse.2022_04_01_mobile`
Yes, both desktop and mobile 👍

2022-08-03 17:39 UTC, rviscomi commented on sql/2022/javascript/fid.sql
> +    date IN ('2022-05-01') AND
```suggestion
    date IN ('2022-06-01') AND
```

2022-08-03 17:39 UTC, rviscomi commented on sql/2022/javascript/frameworks-bytes-by-framework.sql
> +# Sum of JS request bytes per page by framework (2020)
```suggestion
# Sum of JS request bytes per page by framework
```

2022-08-03 17:40 UTC, rviscomi commented on sql/2022/javascript/frameworks-bytes-by-framework.sql
> +#standardSQL
Nit: this file name uses hyphen delimiters while most others use underscores. Change to underscores for consistency.

2022-08-03 17:41 UTC, rviscomi commented on sql/2022/javascript/inp.sql
> +    date IN ('2022-05-01') AND
```suggestion
    date IN ('2022-06-01') AND
```

2022-08-03 17:41 UTC, rviscomi commented on sql/2022/javascript/lighthouse_unminified_js.sql
> +    `httparchive.lighthouse.2022_06_01_mobile`)
All LH queries should utilize the new desktop data (also group by `_TABLE_SUFFIX AS client`)
```suggestion
    `httparchive.lighthouse.2022_06_01_*`)
```

2022-08-03 17:42 UTC, rviscomi commented on sql/2022/javascript/lighthouse_unminified_js_by_3p.sql
> +      `httparchive.lighthouse.2022_06_01_mobile` AS test,
Desktop

2022-08-03 17:43 UTC, rviscomi commented on sql/2022/javascript/lighthouse_unminified_js_bytes.sql
> +    `httparchive.lighthouse.2022_06_01_mobile` AS test
Desktop

2022-08-03 17:43 UTC, rviscomi commented on sql/2022/javascript/lighthouse_vulnerabilities.sql
> +    `httparchive.lighthouse.2022_06_01_mobile`)
Desktop

2022-08-03 17:43 UTC, rviscomi commented on sql/2022/javascript/lighthouse_vulnerable_libraries.sql
> +  `httparchive.lighthouse.2022_06_01_mobile`,
Desktop

2022-08-03 17:44 UTC, rviscomi commented on sql/2022/javascript/module_and_nomodule.sql
> +    `httparchive.almanac.summary_response_bodies`
We should have module/nomodule stats in the custom metric, right?

2022-08-03 17:45 UTC, rviscomi commented on sql/2022/javascript/requests_2022.sql
> +  `httparchive.summary_pages.2022_06_01_*`,
Similar comment as the byte distribution over time, I'd suggest combining them all with `UNION ALL`.

2022-08-03 17:46 UTC, rviscomi commented on sql/2022/javascript/tbt.sql
> +    `httparchive.lighthouse.2022_06_01_mobile`
Desktop

2022-08-03 17:46 UTC, rviscomi commented on sql/2022/javascript/time_to_interactive.sql
> +    `httparchive.lighthouse.2022_06_01_mobile`),
Desktop

2022-08-03 17:46 UTC, rviscomi commented on sql/2022/javascript/unused_js_bytes_distribution.sql
> +  `httparchive.lighthouse.2022_06_01_mobile`,
Desktop

2022-08-03 17:46 UTC, rviscomi commented on sql/2022/javascript/usage_of_document_write.sql
> +        `httparchive.lighthouse.2022_06_01_mobile` AS lighthouse,
Desktop

2022-08-03 17:47 UTC, rviscomi commented on sql/2022/javascript/usage_of_legacy_javascript.sql
> +        `httparchive.lighthouse.2022_06_01_mobile` AS lighthouse,
Desktop

2022-08-03 17:48 UTC, rviscomi commented on sql/2022/javascript/web_components_pct.sql
> +      `httparchive.pages.2021_09_01_*`)
2022?

2022-08-03 17:48 UTC, rviscomi commented on sql/2022/javascript/web_components_specs.sql
> +    `httparchive.pages.2021_09_01_*`),
2022?

2022-08-04 09:09 UTC, kevinfarrugia commented on sql/2022/javascript/bytes_2022.sql
> +  `httparchive.summary_pages.2022_06_01_*`,
Would it be fine if I pick this up afterwards as a separate PR as an improvement rather than a "must-have"?

2022-08-04 12:33 UTC, rviscomi commented on sql/2022/javascript/bytes_2022.sql
> +  `httparchive.summary_pages.2022_06_01_*`,
Sure, not a blocker

2022-08-04 15:00 UTC, rviscomi requested changes

2022-08-04 15:00 UTC, rviscomi commented on sql/2022/javascript/lighthouse_unminified_js_bytes.sql
>    COUNT(0) / SUM(COUNT(0)) OVER () AS pct
Ditto

2022-08-04 15:00 UTC, rviscomi commented on sql/2022/javascript/lighthouse_vulnerabilities.sql
>    COUNT(0) / SUM(COUNT(0)) OVER () AS pct
Ditto

2022-08-04 15:04 UTC, rviscomi approved these changes

2022-08-04 15:10 UTC, merged