WebAssembly 2022 queries
HTTPArchive/almanac.httparchive.org pull request #2951
Opened 2022-05-30 12:45 UTC by JamieWhitMac

Queries for the WebAssembly 2022 chapter ([#2885](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2885))

## WebAssembly adoption
- [ ] % of desktop and mobile websites that use WebAssembly
- [ ] rankings of pages which use WASM compared to the overall rankings of pages in the crawl

## Popular WebAssembly languages
- [ ] counts of WebAssembly files which use each language

## Popular WebAssembly-powered Libraries
- [ ] count of popular wasm modules
- [ ] count of popular wasm modules with unique filenames

## WASM module sizes
- [ ] sizes of wasm modules, both as binaries and raw request sizes

## Post-MVP Extensions
- [ ] count of usages of post-MVP WASM extensions

2022-06-17 17:19 UTC, siakaramalegos commented
Great job so far! Can you update the checkboxes so we get a better idea of how much is left to go?

2022-07-08 16:35 UTC, siakaramalegos commented
Hi @JamieWhitMac it looks like you've written a lot of the queries, but I can't tell if they are finished yet. Can you update your progress using the checkboxes and/or commenting where you're at? Let me know if you need any help.

2022-07-20 11:42 UTC, JamieWhitMac commented
Hi @siakaramalegos, apologies for the slow response. All but two queries are complete as the majority are re-used from last year's Almanac (aside from needing tweaks to dates to bring them up to date, so none are technically 'complete'). I'll be writing the remaining ones, changing the dates on the existing queries, and compiling the results in the coming week.

2022-07-29 17:54 UTC, siakaramalegos commented
@JamieWhitMac just checking in - the analysis needs to be done by the end of the month (in just a few days) to stay on track for writing and publication. How is it going? Do you think you can still hit that deadline? Thanks!

2022-08-01 09:35 UTC, JamieWhitMac commented
Hi @siakaramalegos, I encountered a little setback last week as I had a mistaken assumption about where the wasm data from the 2022 crawls would be. I've updated the comment above to show current progress changing the existing queries, hoping to have them finished ASAP.

2022-08-01 14:26 UTC, siakaramalegos commented
@JamieWhitMac thanks for the update! Also, the analysts channel in Slack can be super helpful if you have a question or need help on a query.

2022-08-15 02:46 UTC, rviscomi commented
@JamieWhitMac is this PR ready for review?

2022-08-17 10:05 UTC, JamieWhitMac commented
@rviscomi it's very close, apologies for delay - should be ready to go in the next couple of days, once I double-check the linting and confirm the data we have is definitely everything we need.

2022-08-17 16:34 UTC, rviscomi commented
Just noticed the linter wasn't running automatically because you're not in the HTTPArchive org on GitHub. I've manually kicked that off and sent you an invite to join now. (Which also gives you more privileges to edit stuff in this repo, like the checklist in #2885)

Also consider marking the PR ready for review now to get early feedback and we can merge it sooner. If there are any follow-up queries needed, those can be added in a separate PR.

2022-08-19 16:13 UTC, rviscomi requested changes

2022-08-19 16:13 UTC, rviscomi commented on sql/2022/webassembly/page_rankings.sql
> +SELECT
This query should also be grouping by client

2022-08-19 16:13 UTC, rviscomi commented on sql/2022/webassembly/language_usage.sql
> +  COUNT(0) AS count
I'd also suggest calculating this as a %
```suggestion
  COUNT(0) AS count,
  SUM(COUNT(0)) OVER (PARTITION BY client) AS total,
  COUNT(0) / SUM(COUNT(0)) OVER (PARTITION BY client) AS pct
```

2022-08-19 16:13 UTC, rviscomi commented on sql/2022/webassembly/popular_by_name.sql
> +  MIN(url) AS url
Is the URL needed?
```suggestion
```

2022-08-19 16:13 UTC, rviscomi commented on sql/2022/webassembly/proposals.sql
> +  COUNTIF(SAFE_CAST(JSON_VALUE(wasm_stats, '$.instr.proposals.atomics') AS INT64) > 0) AS atomics,
Do you also want these stats as %s?

2022-08-20 18:03 UTC, rviscomi commented on sql/2022/webassembly/page_rankings.sql
> +  _rank AS rank,
```suggestion
  client,
  _rank AS rank,
```

2022-08-20 18:03 UTC, rviscomi commented on sql/2022/webassembly/page_rankings.sql
> +  rank
```suggestion
  client,
  rank
```

2022-08-20 18:03 UTC, rviscomi approved these changes

2022-08-20 18:04 UTC, rviscomi commented
Applied code review suggestions. I see that the results sheet seems to have the right data already, so the queries don't necessarily need to be rerun. Merging now.

2022-08-20 18:04 UTC, merged