Update README.md
HTTPArchive/almanac.httparchive.org pull request #2953
Opened 2022-06-01 01:51 UTC by drohe

2022-06-13 13:31 UTC, rviscomi commented
Thanks for working on this @drohe! I've extracted the checklist from the readme and added to the PR comment for easier tracking.

2022-07-30 02:21 UTC, rviscomi submitted a review, later dismissed
General comment about parsing Lighthouse results, applies to all LH queries

2022-07-30 02:21 UTC, rviscomi commented on sql/2022/page-weight/facades-usage.sql
> +    ) AS fail_count
These `REGEXP_CONTAINS` checks actually work fine, but we should use the semantic JSON functions built into BigQuery. For example:

```suggestion
    COUNTIF(JSON_VALUE(report, '$.audits.third-party-facades.score') IS NULL) AS null_count,
    COUNTIF(SAFE_CAST(JSON_VALUE(report, '$.audits.third-party-facades.score') AS FLOAT64) >= 0.9) AS pass_count,
    COUNTIF(SAFE_CAST(JSON_VALUE(report, '$.audits.third-party-facades.score') AS FLOAT64) < 0.9) AS fail_count
```

This also lets you use 0.9 as the pass/fail threshold, which is more consistent with the way Lighthouse scores audits. In this particular case everything is 0 or null, but it generalizes to all audits.

2022-08-09 14:19 UTC, rviscomi commented
@drohe could you take a look at the linter warnings? Hoping to get all analysis PRs merged this week.

2022-08-11 01:51 UTC, drohe reviewed
I think I addressed the linting issues and the request to update to use the JSON

2022-08-11 02:08 UTC, drohe reviewed
linting updates part 2

2022-08-11 03:06 UTC, drohe commented
@rviscomi I'm at a loss on the end of line linting errors from the editorconfig-checker. I've got it set to CRLF in VS Code. Should it be LF?

2022-08-11 14:06 UTC, rviscomi reviewed
Weird I've never seen that warning before. Let's see if deleting/adding the newline from code review helps.

2022-08-11 14:06 UTC, rviscomi commented on sql/2022/page-weight/bytes_per_type.sql
> +  percentile
```suggestion
  percentile

```

2022-08-11 14:06 UTC, rviscomi commented on sql/2022/page-weight/compression-usage.sql
> +  fail_count
```suggestion
  fail_count

```

2022-08-11 14:06 UTC, rviscomi commented on sql/2022/page-weight/facades-usage.sql
> +  fail_count
```suggestion
  fail_count

```

2022-08-11 14:06 UTC, rviscomi commented on sql/2022/page-weight/minified_css_usage.sql
> +  fail_count
```suggestion
  fail_count

```

2022-08-11 14:06 UTC, rviscomi commented on sql/2022/page-weight/minified_js_usage.sql
> +  fail_count
```suggestion
  fail_count

```

2022-08-11 14:06 UTC, rviscomi commented on sql/2022/page-weight/page_weight_trend.sql
> +  client
```suggestion
  client

```

2022-08-11 14:06 UTC, rviscomi commented on sql/2022/page-weight/request_type_distribution.sql
> +  percentile
```suggestion
  percentile

```

2022-08-11 14:06 UTC, rviscomi commented on sql/2022/page-weight/response_format_distribution.sql
> +  percentile
```suggestion
  percentile

```

2022-08-11 14:06 UTC, rviscomi commented on sql/2022/page-weight/response_type_distribution.sql
> +  percentile
```suggestion
  percentile

```

2022-08-11 14:35 UTC, rviscomi commented
Ok that did the trick! In the GitHub editor (press `.`) I changed CRLF to LF.

2022-08-11 14:40 UTC, rviscomi requested changes

2022-08-11 14:40 UTC, rviscomi commented on sql/2022/page-weight/compression-usage.sql
> +  COUNTIF(SAFE_CAST(JSON_VALUE(report, '$.audits.text-compression.score') AS FLOAT64) < 0.9) AS fail_count
For each of these "count" queries, we should also calculate the percent of pages. Something like this:
```suggestion
  COUNTIF(SAFE_CAST(JSON_VALUE(report, '$.audits.text-compression.score') AS FLOAT64) >= 0.9) AS pass_count,
  COUNTIF(SAFE_CAST(JSON_VALUE(report, '$.audits.text-compression.score') AS FLOAT64) < 0.9) AS fail_count,
  COUNT(0) AS total,
  COUNTIF(SAFE_CAST(JSON_VALUE(report, '$.audits.text-compression.score') AS FLOAT64) >= 0.9) / COUNT(0) AS pct_pass,
  COUNTIF(SAFE_CAST(JSON_VALUE(report, '$.audits.text-compression.score') AS FLOAT64) < 0.9) / COUNT(0) AS pct_fail
```

Can you also update the rest of the queries to calculate percents?

2022-08-11 14:40 UTC, rviscomi commented on sql/2022/page-weight/page_weight_trend.sql
> +  REPLACE(SUBSTR(_TABLE_SUFFIX, 0, 10), '_', '') AS date,
Not sure why but YYYY-MM-DD format seems to work best for custom date formatting in sheets, ie to display as "Aug 2022".
```suggestion
  REPLACE(SUBSTR(_TABLE_SUFFIX, 0, 10), '_', '-') AS date,
```

2022-08-15 02:54 UTC, rviscomi commented on sql/2022/page-weight/compression-usage.sql
> +  COUNTIF(SAFE_CAST(JSON_VALUE(report, '$.audits.text-compression.score') AS FLOAT64) < 0.9) AS fail_count
@drohe let me know if I can help at all with this. Want to make sure we give @fellowhuman1101 enough time to write the draft.

2022-08-18 02:10 UTC, drohe commented
added the percentages

2022-08-19 16:02 UTC, rviscomi approved these changes

2022-08-19 16:02 UTC, merged