Media 2022 queries
HTTPArchive/almanac.httparchive.org pull request #2979
Opened 2022-06-19 10:41 UTC by eeeps

Here's our todo list:

## Images

- [ ] What percentage of pages include an <img> element?
- [ ] What percentage of pages make a request for an image resource
- [ ] What percentage of pages have an image or background image as the LCP element?
- [ ] Most common colors
- [ ] Most common colors by popular (and geographically distributed) set of TLDs
- [ ] Ranked list of color spaces
- [ ] Percentage of image resources that are animated
- [ ] Distribution of frames per animated image
- [ ] Time series of format adoption over time (or a simple YoY comparison of percentages)
- [ ] Distribution of pixel counts
- [ ] Distribution of pixel counts excluding single pixel images
- [ ] Ranked list of aspect ratios
- [ ] Distribution of bytesizes
- [ ] Distribution of image bits/pixel
- [ ] Median bits/pixel/frame by format
- [ ] Most common metadata fields
- [ ] Prevalence of ITPC copyright
- [ ] Prevalence of EXIF thumbnails
- [ ] HTML vs CSS vs Javascript vs favicons - counts per page
- [ ] slice bytesizes, pixel counts, formats by embedding context, too
- [ ] Largest favicon
- [ ] Percentage of <img> elements that are lazy-loaded
- [ ] Percentage of lazy-loaded <img> elements that were LCP
- [ ] Percentage of images with an alt or figcaption
    - [ ] weed out unuseful ones
- [ ] Percentage of srcsets containing x descriptors
- [ ] Percentage of srcsets containing w descriptors
- [ ] Distribution of number of candidates in srcsets
- [ ] Usefulness of min->max desnity ranges
- [ ] Distribution of w descriptor errors 
- [ ] Distribution of sizes errors
- [ ] Impact of inaccurate sizes - pixels
- [ ] Impact of innacurate sizes - bytes
- [ ] Most common sizes values
- [ ] Percentage of <picture> elements using type
- [ ] Percentage of <picture> elements using media
- [ ] Most common media queries in media attributes
- [ ] Number of candidates in type attributes
- [ ] Most common type stacks
- [ ] Intrinsic vs extrinsic vs both sizing
- [ ] Percentage of extrinsic-in-one-dimension images that have height and width attributes

--- 

Video

- [ ] percentage of pages including a <video> element
- [ ] Distribution of video durations
- [ ] Ranked list of most-common formats
- [ ] Percentage splits of CSS `display` values of <video> elements
- [ ] Ranked list of <video> element attributes
- [ ] Ranked list of <video> preload values
- [ ] Ranked list of <video> autoplay values
- [ ] Ranked list of <video> width values
- [ ] Split of <video source> vs <video src>
- [ ] Distribution of number of <source> children
- [ ] Most common type stacks

2022-06-19 10:41 UTC, eeeps commented
I've copied over our 2021 queries, which will check off a lot of these boxes. Will reconcile soon!

2022-07-22 17:47 UTC, siakaramalegos commented
@eeeps @akshay-ranganath How are things going with the queries. It looks like you have 57 but the checkboxes are still mostly unchecked so I can't tell. Do you think you can wrap up the queries and have the data and charts in your results sheet by the end of the month? We want to keep the writing on track for publication. Thanks!

2022-07-29 17:53 UTC, siakaramalegos commented
Hi @eeeps @akshay-ranganath can you give me a written description of where you're at/how it's going? See my last comment. We're trying to understand progress on all the chapters. Thanks

2022-08-01 23:27 UTC, eeeps commented
@siakaramalegos Plan A was to get all of the queries written by the end of July; going a bit too far down a couple of rabbit holes regarding the exciting new data from ImageMagick and EXIFTool, plus me not planning for my end-of-month vacation, foiled that plan.

So now we're on to Plan B, with a firm deadline of next Monday the 8th to get all of the queries written and results in, which will leave 3 weeks for writing and editing. Likely we will have to simplify a few queries (e.g., just querying named ICC profiles, rather than trying to figure out every way every format can possibly encode non-sRGB profiles + how EXIFTool reports on them all...), but having a write-about-able set of results in a week's time seems accomplishable.

Thanks for checking in.

2022-08-11 17:55 UTC, eeeps commented
Oh no I made a mess

2022-08-11 18:06 UTC, eeeps commented
Ok I think I cleaned the mess up 😬

2022-08-15 02:48 UTC, rviscomi commented
@eeeps there are a couple of linter errors, otherwise is this PR ready for review?

2022-08-19 16:01 UTC, rviscomi commented
🛎️ @eeeps @akshay-ranganath can we wrap up the remaining queries and mark the PR ready for review? The deadline for having the chapter written, reviewed, and edited is September 1, so it'd be great to finish the analysis and start writing ASAP.

2022-08-20 15:09 UTC, eeeps commented
Still todo:

1. Make the linter happy
2. Finish an Animated GIF query that's very close...
3. BONUS: Leave some notes for future analysts, probably in a comment on this PR

I'd planned on buttoning this up yesterday but it's stretched into today. Today for sure.

2022-08-20 16:09 UTC, rviscomi requested changes
linter suggestions

2022-08-20 16:09 UTC, rviscomi commented on sql/2022/media/video_tag_and_js_player.sql
> +
```suggestion
  client
```

2022-08-20 16:09 UTC, rviscomi commented on sql/2022/media/color_spaces_and_depth.sql
> +ORDER BY count DESC
```suggestion
WITH color_info AS (
  SELECT
    _TABLE_SUFFIX as client,
    JSON_EXTRACT( payload, '$._image_details.magick.depth') AS color_depth,
    JSON_EXTRACT( payload, '$._image_details.magick.colorspace') AS color_space,
    JSON_EXTRACT( payload, '$._image_details.magick.properties.icc:description') AS description
  FROM
    `requests.2022_06_01_*`
  WHERE
    JSON_QUERY(payload, '$._image_details.magick.colorspace') IS NOT NULL
),

totals AS (
  SELECT
    client,
    COUNT(0) AS total
  FROM
    color_info
  GROUP BY
    client
),

counts AS (
  SELECT
    client,
    color_depth,
    color_space,
    description,
    COUNT(0) AS count
  FROM
    color_info
  GROUP BY
    client,
    color_depth,
    color_space,
    description
)

SELECT
  *,
  count / total AS pct
FROM
  counts
JOIN
  totals
USING
  (client)
ORDER BY
  count DESC
```

2022-08-20 16:09 UTC, rviscomi commented on sql/2022/media/image_sizes_per_page_accuracy_impact.sql
> +    getTotalEstimatedWastedLoadedBytes(payload) as totalEstimatedWastedLoadedBytes
```suggestion
    getTotalEstimatedWastedLoadedPixels(payload) AS totalEstimatedWastedLoadedPixels,
    getTotalEstimatedWastedLoadedBytes(payload) AS totalEstimatedWastedLoadedBytes
```

2022-08-20 16:09 UTC, rviscomi commented on sql/2022/media/lcp_element_data.sql
> +  )
```suggestion
)
```

2022-08-20 16:10 UTC, rviscomi commented
> BONUS: Leave some notes for future analysts, probably in a comment on this PR

I'd suggest creating something like a "Notes for 2023" section in the [README](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2022/media/README.md)

2022-08-20 17:43 UTC, rviscomi requested changes
Missed a couple of linter errors

2022-08-20 17:43 UTC, rviscomi commented on sql/2022/media/video_tag_and_js_player.sql
> +  client
```suggestion
#standardSQL
# get all pages with video nodes
# along with all pages with video js files
# check if video js is imported when a page has a video element or not

CREATE TEMPORARY FUNCTION get_media_info(media_string STRING)
RETURNS STRUCT<
  num_video_nodes INT64
> LANGUAGE js AS '''
var result = {};
try {
    var media = JSON.parse(media_string);

    if (Array.isArray(media) || typeof media != 'object') return result;

    result.num_video_nodes = media.num_video_nodes;

} catch (e) {}
return result;
''';

SELECT
  client,
  COUNTIF(video_nodes) / COUNT(0) AS video_tag_pct,
  COUNTIF(player IS NOT NULL) / COUNT(0) AS js_video_player_pct,
  COUNTIF(video_nodes AND player IS NOT NULL) / COUNT(0) AS both_video_tag_js_player_pct
FROM (
  SELECT
    client,
    media_info.num_video_nodes > 0 AS video_nodes,
    player
  FROM (
    SELECT
      _TABLE_SUFFIX AS client,
      url,
      get_media_info(JSON_EXTRACT_SCALAR(payload, '$._media')) AS media_info
    FROM
      `httparchive.pages.2022_06_01_*`)
  FULL OUTER JOIN (
    SELECT
      client,
      url,
      LOWER(REGEXP_EXTRACT(url, '(?i)(hls|video|shaka|jwplayer|brightcove-player-loader|flowplayer)[(?:\\.min)]?\\.js')) AS player
    FROM
      `httparchive.almanac.requests`
    WHERE
      date = '2022-06-01' AND
      type = 'script'
    GROUP BY
      client,
      url,
      page,
      player)
  USING (client, url)
  GROUP BY
    client,
    url,
    video_nodes,
    player
  HAVING
    video_nodes OR player IS NOT NULL)
GROUP BY
  client
ORDER BY
  client

```

2022-08-20 17:43 UTC, rviscomi commented on sql/2022/media/color_spaces_and_depth.sql
> +    _TABLE_SUFFIX as client,
```suggestion
    _TABLE_SUFFIX AS client,
```

2022-08-20 17:54 UTC, rviscomi requested changes

2022-08-20 17:54 UTC, rviscomi commented on sql/2022/media/image_decode_usage.sql
> +    `httparchive.pages.2022_07_01_*`)
```suggestion
    `httparchive.pages.2022_06_01_*`)
```

2022-08-20 17:54 UTC, rviscomi commented on sql/2022/media/animated_gif_count.sql
> +  COUNT(0) as total_gifs,
```suggestion
  COUNT(0) AS total_gifs,
```

2022-08-20 17:54 UTC, rviscomi commented on sql/2022/media/animated_gif_count.sql
> +FROM `requests.2022_06_01_*`
```suggestion
FROM
  `requests.2022_06_01_*`
```

2022-08-20 17:54 UTC, rviscomi commented on sql/2022/media/animated_gif_count.sql
> +  COUNTIF( CAST( JSON_VALUE(payload, '$._image_details.animated') AS BOOL ) ) total_animated_gifs,
```suggestion
  COUNTIF( CAST( JSON_VALUE(payload, '$._image_details.animated') AS BOOL ) ) AS total_animated_gifs,
```

2022-08-20 17:54 UTC, rviscomi commented on sql/2022/media/animated_gif_count.sql
> +  JSON_VALUE(payload, '$._image_details.detected_type') = "gif" AND
```suggestion
  JSON_VALUE(payload, '$._image_details.detected_type') = 'gif' AND
```

2022-08-20 17:54 UTC, rviscomi commented on sql/2022/media/animated_gif_count.sql
> +LANGUAGE js AS '''
Tip: use `r'''` so that you don't need to escape regexp characters
```suggestion
LANGUAGE js AS r'''
```

2022-08-20 17:54 UTC, rviscomi commented on sql/2022/media/animated_gif_count.sql
> +const matched = imageMagickNumberString.match( /(\\d+)\\.?(\\d+)?M$/ );
```suggestion
const matched = imageMagickNumberString.match( /(\d+)\.?(\d+)?M$/ );
```

2022-08-20 17:56 UTC, rviscomi commented on sql/2022/media/image_decode_usage.sql
> +    `httparchive.pages.2022_07_01_*`)
Leaving this one unresolved as a reminder for you to rerun the query with June data

2022-08-20 18:09 UTC, eeeps commented
I see that there are some other queries that we haven't got results for in the sheet. I'll straighten all of that out. But with that last Animated Gif query, the queries themselves are, indeed, ready for review.

2022-08-20 19:10 UTC, rviscomi approved these changes

2022-08-20 19:10 UTC, merged