Jamstack 2022 Queries
HTTPArchive/almanac.httparchive.org pull request #2992
Opened 2022-06-27 09:05 UTC by whitep4nth3r

Draft PR with the following queries noted:

1. Jamstack sites are fast
[ ] Lighthouse Performance score
[ ] Largest Contentful Paint (this is also referenced in item 2, I'm not sure which one it fits in)

2. Jamstack sites are resilient (and pre-rendered)
[ ] Rendered content sizes (reuse SEO chapter query https://github.com/HTTPArchive/custom-metrics/blob/main/dist/wpt_bodies.js)
[ ] Largest Contentful Paint?
[ ] How much the content changes post-load

3. Jamstack sites are cached for a long time
[ ] Age header

4. The Jamstack category is growing
[ ] Percentage of "new" sites in crawl that meet the defined criteria of "fast", "resilient" and "cached"

2022-07-13 20:44 UTC, tunetheweb commented
@seldo @GregBrimble any progress on this? Getting quick concerned with the Jamstack chapter falling behind. Let me know if there’s anything I can do to help.

2022-07-13 21:58 UTC, seldo commented
Sorry Barry, this was done as far as I'm concerned, and simply not merged -- my plan next week was to actually run these queries against some previous years. Is there more you'd expect prior to merging this?

2022-07-13 22:02 UTC, tunetheweb commented
Ah that’s great news.

If you could add the queries to this branch when you get a chance, we’ll give them a quick code review first, to save you having to rerun if we spot any problems.

2022-07-13 22:08 UTC, seldo commented
Sure thing. I'm assuming what we should be doing is adding SQL files to `sql/2022/jamstack` along the lines of https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2021/javascript/frameworks_libraries.sql or is there a more sophisticated way to do this? (And is it okay if that's next week?)

2022-07-13 22:11 UTC, tunetheweb commented
Yup that’s it. Next week is more than fine now I know you’ve actually worked/are working on them. Was just a bit worried it was all too quiet and worried nothing was happening.

So next milestone is 1st August to have them added, reviewed, merged and run. And then comes the writing about all that lovely data!

2022-07-21 21:44 UTC, seldo commented
Okay, I've done the initial queries and created a combined query that allows us to find all the URLs that match our various criteria and then a join that finds all the sites that match all of them. I've been inspecting the resulting URLs and they certainly all seem very jamstacky! There are quite a small number so I imagine picking "must exceed median" is quite stringent (as it excludes anybody at, or close to the median on one or more metrics).

Next steps:
* Examine the matching URLs for false positives (expecting very few)
* Try relaxing one or more parameters to include URLs close to the thresholds and see when we start getting a lot of false positives
* Having picked thresholds we like, do a longitudinal pass across previous years to see if this group is growing or shrinking and how fast

2022-07-24 19:27 UTC, GregBrimble commented
Hey folks, sorry, I've been pretty preoccupied with other stuff this year, and @seldo has already done a great job with the queries so far. Looks like it's pretty much just going to be relatively subjective tweaking of thresholds now. If it's alright, I'll bow out and let you finish them off. Sorry again, and good luck with the chapter!

2022-07-25 10:47 UTC, tunetheweb requested changes

2022-07-25 10:47 UTC, tunetheweb commented on sql/2022/jamstack/candidate_urls.sql
> +),
This is available as a field in `httparchive.almanac.requests` which makes it significantly cheaper to query. The `almanac` dataset is an optimised version of the monthly datasets with certain keyfields (like this one) pulled out form the `payload` body to make them easier (and quicker and cheaper) to query.

Also we are using June not July for the almanac this year.

Plus we should look at both mobile and desktop.

```suggestion
with headers as (
  SELECT
    client,
    url,
    response_headers as headers_array
  FROM
    `httparchive.almanac.requests`
  WHERE
    date = '2022-06-01'
),
```

This is 1 TB compared to 12 TB.

And you will probably be able to merge this CTE into the next one now.

2022-07-25 10:47 UTC, tunetheweb commented on sql/2022/jamstack/candidate_urls.sql
> +    CAST(JSON_EXTRACT(report, '$.audits.cumulative-layout-shift.numericValue') as NUMERIC) as cls
We should not use the lighthouse data for this. Instead either use the CrUX data (in the `pages` data set) if wanting home page data, or the CrUX data in `chrome-ux-report.materialized.device_summary` dataset if wanting to use the whole origin data.

2022-07-25 10:47 UTC, tunetheweb commented on sql/2022/jamstack/candidate_urls.sql
> +  FROM `httparchive.lighthouse.2022_07_01_mobile`
If you are using lighthouse (which, as I say I don't think we should use for LCP or CLS), then note we have desktop lighthouse data this year so should look to query for both.

2022-07-25 10:47 UTC, tunetheweb commented on sql/2022/jamstack/candidate_urls.sql
> +  and cls < 0.06
Why are these levels chosen? Why not the CWV levels that more people are likely to know?

2022-07-25 10:47 UTC, tunetheweb commented on sql/2022/jamstack/candidate_urls.sql
> +performance_filtered as (
This three CTEs could easily be merged into one.

2022-07-25 10:47 UTC, tunetheweb commented on sql/2022/jamstack/candidate_urls.sql
> +  where perf_rounded > 0.31
Again, why this score? Seems arbitary.

2022-07-25 10:47 UTC, tunetheweb commented on sql/2022/jamstack/distribution_age_headers.sql
> +-- we're using 2022-07-01 run as the baseline because values change every year
Shouldn't this only be looking at the HTML page request, rather than all requests?

2022-07-25 10:47 UTC, tunetheweb commented on sql/2022/jamstack/distribution_cls.sql
> +  FROM `httparchive.lighthouse.2022_07_01_mobile`
Again better to use CrUX data.

2022-07-25 10:47 UTC, tunetheweb commented on sql/2022/jamstack/distribution_lcp.sql
> +  FROM `httparchive.lighthouse.2022_07_01_mobile`
Use CrUX data.

2022-08-07 14:10 UTC, tunetheweb commented
@seldo any update on this? We're now nearly a week past when analysis was due so a little concerned that we're not going to make the publish date...

2022-08-14 18:40 UTC, tunetheweb requested changes

2022-08-14 18:40 UTC, tunetheweb commented on sql/2022/jamstack/distribution_age_headers_desktop.sql
> +-- we're using 2022-06-01 run as the baseline because values change every year
This looks at the age of ALL requests. Including analytics pixesl and the like which may be short.

We should restrict this to home page only surely? Using the `almanac dataset` makes this easier as it has a `firstHTML` field and also pulls the `age` field out for querying.

We also usually include both desktop and mobile in the one query:

```sql
SELECT
  client,
  date,
  COUNT(0) AS total,
  COUNTIF(resp_age IS NOT NULL AND resp_age != '') AS age,
  COUNTIF(resp_age IS NULL OR resp_age = '') AS no_age,
  COUNTIF(resp_age IS NOT NULL AND resp_age != '') / COUNT(0) AS pct_age,
  COUNTIF(resp_age IS NULL OR resp_age = '') / COUNT(0) AS pct_no_age,
FROM
  `httparchive.almanac.requests`
WHERE
  firstHtml
GROUP BY
  client,
  date
ORDER BY
  client,
  date
```

2022-08-14 18:40 UTC, tunetheweb commented on sql/2022/jamstack/candidate_urls_count.sql
> +    CAST(JSON_EXTRACT(payload, "$['_chromeUserTiming.CumulativeLayoutShift']") AS NUMERIC) AS cls
As discussed suggestion is to use CrUX data, rather than Lighthouse.

2022-08-14 18:40 UTC, tunetheweb commented on sql/2022/jamstack/r1_jamstackishness_over_time/candidate_urls_count_2020_06_01_desktop.sql
> +-- step 3.1: get URLs and CLS times from chrome user timings
We expect all queries to be in top level folder, rather than sub-folders.

2022-08-14 18:40 UTC, tunetheweb commented on sql/2022/jamstack/generate_queries.mjs
> +// But the generated files are also checked in
You can just either use the `almanac` data set (which by definition only has almanac years), or use this:"

```sql
SELECT
  IF(ENDS_WITH(_TABLE_SUFFIX, 'desktop'), 'desktop', 'mobile') AS client,
  REGEXP_REPLACE(_TABLE_SUFFIX, r'(\d+)_(\d+)_(\d+).*', r'\1-\2-\3') AS date,
  xxx
FROM
  `httparchive.requests.*
WHERE
  (_TABLE_SUFFIX like '2020_08_01%' OR _TABLE_SUFFIX like '2020_07_01%' OR _TABLE_SUFFIX like '2022_06_01%')
```

This only charges you for the tables you query.

2022-08-17 18:10 UTC, tunetheweb approved these changes

2022-08-17 18:16 UTC, merged