Translation of webassembly chapter to Japanese
HTTPArchive/almanac.httparchive.org pull request #3405
Opened 2023-05-01 09:21 UTC by ksakae1216

Please review for me.
Part of [#586](https://github.com/HTTPArchive/almanac.httparchive.org/issues/586)

2023-05-03 13:32 UTC, tunetheweb requested changes

2023-05-03 13:32 UTC, tunetheweb commented on src/content/ja/2022/webassembly.md
> +  caption="Number of Wasm responses.",
Could you translate this caption?

2023-05-03 13:32 UTC, tunetheweb commented on src/content/ja/2022/webassembly.md
> +  caption="Cross-origin WebAssembly usage.",
And this one?

2023-05-05 02:09 UTC, ksakae1216 reviewed
@tunetheweb Thanks, I translated.
Please check.

2023-05-05 02:09 UTC, ksakae1216 commented on src/content/ja/2022/webassembly.md
> +  caption="Number of Wasm responses.",
Thanks, I translated.

2023-05-05 02:09 UTC, ksakae1216 commented on src/content/ja/2022/webassembly.md
> +  caption="Cross-origin WebAssembly usage.",
Thanks, I translated.

2023-05-05 08:42 UTC, tunetheweb approved these changes

2023-05-05 08:42 UTC, merged