add pdf artifact upload step
HTTPArchive/almanac.httparchive.org pull request #3410
Opened 2023-05-04 09:03 UTC by max-ostapenko

- [x] generated PDFs are temporarily stored in Action Artifacts
- [x] deployment script uses artifact ZIP as a source for deployed PDFs
- [x] PDF files are ignored in the repo moving forward

2023-05-05 10:37 UTC, tunetheweb commented
How's this looking @max-ostapenko ? About to do a release, but will hold off for a day or two if you think this is close to being completed and wanna test it out on a release?

Still not sure how you can download these assets locally?

2023-05-05 11:21 UTC, max-ostapenko commented
@tunetheweb in progress, checking both artifacts and LFS.
Will adapt `src/tools/scripts/deploy.sh` and then you can test it out for your release.

Any other scripts impacted?

2023-05-05 11:23 UTC, tunetheweb commented
Cool will hold off on release then.

I think it should just be that script and the action which generates the PDF.

2023-05-05 17:55 UTC, max-ostapenko commented on src/tools/scripts/deploy.sh
> +#read -sp 'Enter your Github personal access token: ' GITHUB_TOKEN
@tunetheweb please adjust to whatever is preferred option to pass GITHUB_TOKEN value.
Here I tested with `.env` file and user input.

2023-05-06 06:51 UTC, tunetheweb requested changes
This is a VERY nice solution to the problem. Thanks SO much for figuring this out.

Just a few small comments and then think good to merge.

2023-05-06 06:51 UTC, tunetheweb commented on src/tools/scripts/deploy.sh
> +#read -sp 'Enter your Github personal access token: ' GITHUB_TOKEN
Let's just get deployers to set a GITHUB_TOKEN env variable themselves and remove these lines.

Can we add this to here some where? https://github.com/HTTPArchive/almanac.httparchive.org/blob/bed8e5eab20f28633dd2040562379023b7628723/src/README.md?plain=1#L321

Should also explain how to generate an access token and the permission it requires (looks to me `public_repo`).

Also might need to update these steps: https://github.com/HTTPArchive/almanac.httparchive.org/blob/bed8e5eab20f28633dd2040562379023b7628723/src/README.md?plain=1#L359-L372

2023-05-08 20:42 UTC, tunetheweb commented on src/README.md
> +- Downloade latest e-books from Github Action artifacts
```suggestion
- Download latest e-books from Github Action artifacts
```

2023-05-08 20:45 UTC, tunetheweb commented on src/README.md
> +Use existing or create a new token [in GitHub.com](https://github.com/settings/personal-access-tokens/new). In token configuration select *Repository access = Public Repositories (read-only)*.
```suggestion
Use an existing token or create a new token [in GitHub.com](https://github.com/settings/personal-access-tokens/new). In token configuration select *Repository access = Public Repositories (read-only)*.
```

2023-05-08 20:46 UTC, tunetheweb commented on src/README.md
> +export GITHUB_TOKEN=github_pat_...
My token begins with `ghp_` not `github_pat_`:

```suggestion
export GITHUB_TOKEN=...
```

2023-05-08 22:29 UTC, tunetheweb commented
Thanks again for this @max-ostapenko . I'm actually travelling for the next few days so will pick this up after that if you don't mind. But looks good to merge to me.

2023-05-09 08:34 UTC, max-ostapenko commented
Enjoy the travel, and let me know if I can assist further.

2023-05-16 14:13 UTC, tunetheweb approved these changes

2023-05-16 14:13 UTC, merged