Font 2024 queries
HTTPArchive/almanac.httparchive.org pull request #3667
Opened 2024-05-22 15:18 UTC by konfirmed

## To be added 

- [ ] Font Usage
- [ ] ...

2024-07-13 07:33 UTC, IvanUkhov commented
Oh, I have just stumbled upon this PR. I have I think this is obsolete due to https://github.com/HTTPArchive/almanac.httparchive.org/pull/3696 and can be closed. The queries from 2022 have been updated to the new data format and reorganized according to the chapter's structure.

2024-08-24 14:16 UTC, mgifford commented on sql/2024/fonts/color_font_usage.sql
> +    `httparchive.pages.2022_06_01_*`
This should be using `httparchive.all.pages` and the date is still for 2022.

2024-08-24 14:17 UTC, mgifford requested changes
Just noting the obvious.

2024-08-24 14:18 UTC, mgifford commented
Sorry @IvanUkhov are the fonts being tracked elsewhere? The SQL definitely needs to be rewritten for the new format.

2024-08-24 15:13 UTC, IvanUkhov commented
@mgifford, please consider the other PR to be the primary one.

2024-08-25 20:52 UTC, closed without merging