Privacy Sql Tracking Detection Using Easylist Adservers
HTTPArchive/almanac.httparchive.org pull request #3730
Opened 2024-08-14 15:10 UTC by hadiamjad

New queries added for this year's chapter
- [ ] easylist_tracker_detection.sql

New util added for this year's chapter
- [ ] populate_easylist_adserver.py

2024-08-15 00:07 UTC, max-ostapenko commented
Before pushing the changes, you can lint the code in your branch:
```
python3 -m venv src/.venv
source src/.venv/bin/activate
pip install -r src/requirements.txt
sqlfluff fix sql/2024/privacy/
```

2024-08-15 00:14 UTC, max-ostapenko requested changes

2024-08-15 00:14 UTC, max-ostapenko commented on sql/2024/privacy/tracking-detection/easylist_adservers.csv
As you have provided the script, no need for the data snapshot in the repo.
Please remove.

2024-08-15 09:29 UTC, max-ostapenko commented
@hadiamjad FYI I pointed this PR base to the Privacy chapter PR, so that we can merge all chapter in one step eventually.
Looking forward to your linting adjustments to merge this.

2024-08-15 14:10 UTC, tunetheweb commented
> @hadiamjad FYI I pointed this PR base to the Privacy chapter PR, so that we can merge all chapter in one step eventually. Looking forward to your linting adjustments to merge this.

@max-ostapenko you might wanna update the Privacy chapter PR to latest version of `main` to hide the irrelevant changes in this PR (and stop those annoying diff comments being added to this PR, which happens when it thinks you're changing certain things).

2024-08-15 14:43 UTC, max-ostapenko commented
> @max-ostapenko you might wanna update the Privacy chapter PR to latest version of `main` to hide the irrelevant changes in this PR (and stop those annoying diff comments being added to this PR, which happens when it thinks you're changing certain things).

@tunetheweb would you suggest to do it with merge commit or rebase to make it clean?

2024-08-15 14:46 UTC, tunetheweb commented
I think a merge commit on the `privacy-sql-2024` branch will be fine. I hate rebasing :-)

2024-08-16 21:20 UTC, max-ostapenko approved these changes

2024-08-16 21:37 UTC, max-ostapenko commented
> I think a merge commit on the `privacy-sql-2024` branch will be fine. I hate rebasing :-)

I merged `main` into Privacy PR and then also here - the diff was only growing 🤔 
Seems I still need to learn about git behavior :)

2024-08-16 21:48 UTC, merged