Translation of page-weight chapter to Japanese
HTTPArchive/almanac.httparchive.org pull request #3777
Opened 2024-09-24 07:55 UTC by ksakae1216

Please review for me.
Part of [#586](https://github.com/HTTPArchive/almanac.httparchive.org/issues/586)

2024-09-25 11:50 UTC, tunetheweb requested changes
LGTM

2024-09-25 11:50 UTC, tunetheweb commented on src/content/ja/2022/page-weight.md
> +dwsmart_bio: Dave Smart is a developer and technical search engine consultant at <a hreflang="en" href="https://tamethebots.com">Tame the Bots</a>. They love building tools and experimenting with the
Can we translate this?

2024-09-25 11:50 UTC, tunetheweb commented on src/content/ja/2022/page-weight.md
> +editors: []
Could you add me as an editor (also in other langs if you don't mind) as I did edit this in #3159

2024-09-26 08:13 UTC, ksakae1216 commented on src/content/ja/2022/page-weight.md
> +dwsmart_bio: Dave Smart is a developer and technical search engine consultant at <a hreflang="en" href="https://tamethebots.com">Tame the Bots</a>. They love building tools and experimenting with the
@tunetheweb Thanks, I translated

2024-09-26 08:53 UTC, tunetheweb approved these changes

2024-09-26 08:59 UTC, merged